kind: Service
apiVersion: v1
metadata:
  name: webcat
spec:
  selector:
    run: webcat-node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
